
(() => {
  'use strict';
  const canvas=document.getElementById('canvas'), ctx=canvas.getContext('2d'), game=document.getElementById('game');
  const $=id=>document.getElementById(id), scoreEl=$('score'),bestEl=$('best'),overlay=$('overlay'), phaseEl=$('phase'),powerEl=$('powerBadge');
  let W=800,H=400,dpr=1,last=0,raf=0,running=false,paused=false,dead=false,sound=true;
  let difficulty='normal',mode='classic',score=0,best=Number(localStorage.getItem('rex-run-best')||0),speed=260,world=0,day=0,spawn=0,powerSpawn=6,shake=0,particles=[],clouds=[],obstacles=[],powers=[];
  let audioCtx=null,deathTimer=0,deathFlash=0;
  const player={x:100,y:0,w:42,h:55,vy:0,ground:0,jumps:0,run:0,blink:0,shield:0,slow:0,double:0,magnet:0,star:0,boost:0,death:0};
  const configs={easy:{speed:225,gap:1.25},normal:{speed:260,gap:1.02},hard:{speed:300,gap:.8}};
  bestEl.textContent=String(best).padStart(5,'0');
  function initAudio(){if(!audioCtx)audioCtx=new (window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume()}
  function tone(type){if(!sound)return;try{initAudio();const o=audioCtx.createOscillator(),g=audioCtx.createGain(),now=audioCtx.currentTime;const notes={jump:[420,.1,'square'],collect:[680,.16,'sine'],hit:[110,.22,'sawtooth'],death:[160,.55,'sawtooth'],start:[300,.2,'triangle'],pause:[220,.12,'sine']}[type]||[300,.1,'sine'];o.type=notes[2];o.frequency.setValueAtTime(notes[0],now);o.frequency.exponentialRampToValueAtTime(type==='death'?55:notes[0]*1.7,now+notes[1]);g.gain.setValueAtTime(.0001,now);g.gain.exponentialRampToValueAtTime(.12,now+.015);g.gain.exponentialRampToValueAtTime(.0001,now+notes[1]);o.connect(g).connect(audioCtx.destination);o.start(now);o.stop(now+notes[1]+.02)}catch(e){}}
  function resize(){const r=canvas.getBoundingClientRect();dpr=Math.min(devicePixelRatio||1,2);W=Math.max(320,r.width);H=Math.max(260,r.height);canvas.width=W*dpr;canvas.height=H*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);player.ground=H-57; if(!running) draw();}
  addEventListener('resize',resize); resize();
  function setText(){phaseEl.textContent=(day<.5?'DEN':'NOC')+' â€˘ '+({easy:'EASY',normal:'NORMAL',hard:'HARD'}[difficulty]);game.classList.toggle('night',day>=.5)}
  function setDiff(v){difficulty=v;document.querySelectorAll('#difficulty .choice').forEach(x=>x.classList.toggle('active',x.dataset.diff===v))}
  document.querySelectorAll('#difficulty .choice').forEach(b=>b.onclick=()=>setDiff(b.dataset.diff));
  document.querySelectorAll('#mode .choice').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;document.querySelectorAll('#mode .choice').forEach(x=>x.classList.toggle('active',x===b))});
  function reset(){const c=configs[difficulty];score=0;speed=c.speed;world=0;day=0;spawn=.8;powerSpawn=5;dead=false;deathTimer=0;deathFlash=0;paused=false;obstacles=[];powers=[];particles=[];player.y=player.ground-player.h;player.vy=0;player.jumps=0;player.shield=0;player.slow=0;player.double=0;player.magnet=0;player.star=0;player.boost=0;player.death=0;shake=0;updateScore();setText()}
  function start(){initAudio();tone('start');reset();running=true;overlay.classList.add('hide');last=performance.now();cancelAnimationFrame(raf);raf=requestAnimationFrame(loop)}
  function finishDeath(){running=false;dead=true;best=Math.max(best,Math.floor(score));localStorage.setItem('rex-run-best',best);bestEl.textContent=String(best).padStart(5,'0');$('overEyebrow').textContent='bÄ›h skonÄŤil';$('overTitle').textContent='SkĂłre '+Math.floor(score);$('overText').textContent=best===Math.floor(score)?'NovĂ˝ rekord! MÄ›sto dnes patĹ™Ă­ tobÄ›.':'JeĹˇtÄ› jeden pokus? PĹ™ekĂˇĹľky ÄŤekajĂ­.';$('startBtn').textContent='BÄ›hat znovu';overlay.classList.remove('hide')}
  function end(){if(dead)return;dead=true;deathTimer=.8;player.death=0;tone('death');shake=13;burst(player.x+21,player.y+27,'#ffcf5a',28);burst(player.x+21,player.y+27,'#ff6574',16)}
  function jump(){if(!running||paused||dead)return;if(player.jumps<1||(player.double&&player.jumps<2)){initAudio();tone('jump');player.vy=-620;player.jumps++;burst(player.x+20,player.ground+3,'#c8ffe0',5)}}
  function move(dir){if(!running||paused)return;player.x=Math.max(35,Math.min(W-80,player.x+dir*38))}
  function updateScore(){scoreEl.textContent=String(Math.floor(score)).padStart(5,'0')}
  function addObstacle(){const tall=Math.random()<.33;obstacles.push({x:W+30,w:tall?26:35+Math.random()*22,h:tall?62:32+Math.random()*17,type:tall?'tower':'rock'})}
  function addPower(){const kinds=['shield','slow','double','magnet','star','boost'],kind=kinds[Math.floor(Math.random()*kinds.length)];powers.push({x:W+20,y:player.ground-55-Math.random()*85,r:13,kind,t:0})}
  function hit(a,b){return a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y}
  function box(o){return{x:o.x,y:o.y,w:o.w||o.r*2,h:o.h||o.r*2}}
  function collect(p){if(p.kind==='shield')player.shield=7;if(p.kind==='slow')player.slow=6;if(p.kind==='double')player.double=1;if(p.kind==='magnet')player.magnet=7;if(p.kind==='star')player.star=7;if(p.kind==='boost')player.boost=6;tone('collect');powerEl.textContent={shield:'Ĺ TĂŤT',slow:'ZPOMALENĂŤ',double:'DVOJSKOK',magnet:'MAGNET',star:'HVÄšZDA',boost:'BOOST'}[p.kind];powerEl.classList.add('show');burst(p.x,p.y,p.kind==='shield'?'#72f1b8':p.kind==='star'?'#fff06a':'#ffd66d',16)}
  function burst(x,y,color,n=8){for(let i=0;i<n;i++)particles.push({x,y,vx:(Math.random()-.5)*170,vy:(Math.random()-.8)*170,life:.6+Math.random()*.5,color,r:2+Math.random()*3})}
  function update(dt){if(dead){deathTimer-=dt;player.death=Math.min(1,player.death+dt/0.8);player.vy+=1500*dt;player.y+=player.vy*dt;shake=Math.max(0,shake-dt*16);particles.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=240*dt;p.life-=dt});particles=particles.filter(p=>p.life>0);if(deathTimer<=0)finishDeath();return}const slow=player.slow?0.52:1;const dist=speed*(player.boost?1.28:1)*slow*dt;world+=dist;score+=dist*.045*(player.star?2:1);day=(Math.sin(world/3500)+1)/2;speed=configs[difficulty].speed+Math.min(135,score*.16);player.run+=dt*12;player.blink=Math.max(0,player.blink-dt);if(player.shield)player.shield-=dt;if(player.slow)player.slow-=dt;if(player.magnet)player.magnet-=dt;if(player.star)player.star-=dt;if(player.boost)player.boost-=dt;if(!player.shield&&!player.slow&&!player.double&&!player.magnet&&!player.star&&!player.boost)powerEl.classList.remove('show');
    player.vy+=1500*dt;player.y+=player.vy*dt;if(player.y>=player.ground-player.h){player.y=player.ground-player.h;player.vy=0;player.jumps=0}
    spawn-=dt;if(spawn<=0){addObstacle();spawn=configs[difficulty].gap+Math.random()*.7-Math.min(.35,score/9000)}powerSpawn-=dt;if(powerSpawn<=0){addPower();powerSpawn=8+Math.random()*8}
    obstacles.forEach(o=>o.x-=dist);powers.forEach(p=>{p.x-=dist;p.t+=dt;if(player.magnet){const dx=player.x+21-p.x,dy=player.y+27-p.y,dd=Math.hypot(dx,dy);if(dd<190){p.x+=dx*dt*2.8;p.y+=dy*dt*2.8}}});obstacles=obstacles.filter(o=>o.x>-90);powers=powers.filter(p=>p.x>-50);
    const pb={x:player.x+7,y:player.y+6,w:player.w-13,h:player.h-8};for(const o of obstacles){const ob={x:o.x,y:player.ground-o.h,w:o.w,h:o.h};if(hit(pb,ob)){if(player.shield>0||player.star>0){if(player.shield)player.shield=0;burst(o.x,o.y,player.star?'#fff06a':'#72f1b8',20);o.x=-200;shake=8;tone('hit')}else{end();return}}}for(const p of powers){const q=box(p);q.x-=p.r;q.y-=p.r;if(hit(pb,q)){collect(p);p.x=-200}}particles.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=240*dt;p.life-=dt});particles=particles.filter(p=>p.life>0);shake=Math.max(0,shake-dt*20);updateScore();setText()}
  function sky(){const n=day;const top=lerp('#84d9ec','#101b42',n),bot=lerp('#d9f4d9','#27345c',n);const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,top);g.addColorStop(1,bot);ctx.fillStyle=g;ctx.fillRect(0,0,W,H);if(n>.48){ctx.fillStyle='#fff5b855';ctx.beginPath();ctx.arc(W*.78,65,24,0,7);ctx.fill()}else{ctx.fillStyle='#ffe58a';ctx.beginPath();ctx.arc(W*.78,62,31,0,7);ctx.fill()}for(const c of clouds){c.x-=.12;if(c.x<-100)c.x=W+80;ctx.fillStyle=n>.5?'#a6b5d020':'#fff9e044';ctx.beginPath();ctx.ellipse(c.x,c.y,c.s*1.7,c.s*.5,0,0,7);ctx.ellipse(c.x+c.s,c.y-5,c.s,c.s*.55,0,0,7);ctx.fill()}}
  function lerp(a,b,t){const ca=a.match(/\w\w/g).map(x=>parseInt(x,16)),cb=b.match(/\w\w/g).map(x=>parseInt(x,16));return`rgb(${ca.map((v,i)=>Math.round(v+(cb[i]-v)*t)).join(',')})`}
  function draw(){sky();ctx.save();if(shake)ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);const ground=player.ground;ctx.fillStyle=day<.5?'#4f9870':'#263d5b';ctx.fillRect(0,ground,W,H-ground);ctx.fillStyle=day<.5?'#91db92':'#466a84';ctx.fillRect(0,ground,W,3);for(let x=-(world%70);x<W;x+=70){ctx.fillStyle=day<.5?'#30644f':'#1c2c46';ctx.fillRect(x,ground+25,36,3)}for(let i=0;i<5;i++){const x=(i*210-world*.08)% (W+180)-100;ctx.fillStyle=day<.5?'#387c73':'#1c314b';ctx.fillRect(x,ground-55,10,55);ctx.fillRect(x-24,ground-49,58,8);ctx.fillRect(x-17,ground-68,43,7)}
    obstacles.forEach(o=>{ctx.fillStyle=o.type==='tower'?'#283c55':'#405f58';ctx.beginPath();ctx.roundRect(o.x,ground-o.h,o.w,o.h,7);ctx.fill();ctx.fillStyle='#b7e5d477';for(let y=ground-o.h+10;y<ground-7;y+=17)ctx.fillRect(o.x+7,y,5,6);ctx.fillStyle='#ffcf5a';ctx.fillRect(o.x+o.w/2-3,ground-o.h-7,6,7)});
    powers.forEach(p=>{const col={shield:'#72f1b8',slow:'#8bd6ff',double:'#ffd56b',magnet:'#f092ff',star:'#fff06a',boost:'#ff8d5c'}[p.kind];const label={shield:'S',slow:'T',double:'2',magnet:'M',star:'â…',boost:'B'}[p.kind];ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.t*2);ctx.fillStyle=col;ctx.shadowColor=col;ctx.shadowBlur=16;ctx.beginPath();ctx.moveTo(0,-p.r);ctx.lineTo(p.r,0);ctx.lineTo(0,p.r);ctx.lineTo(-p.r,0);ctx.closePath();ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#102033';ctx.font='bold 13px sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(label,0,1);ctx.restore()});
    drawPlayer();particles.forEach(p=>{ctx.globalAlpha=Math.max(0,p.life);ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,7);ctx.fill();ctx.globalAlpha=1});ctx.restore()}
  function drawPlayer(){const x=player.x,y=player.y,run=Math.sin(player.run)*4;ctx.save();ctx.translate(x+21,y+27);if(player.death){ctx.rotate(player.death*1.45);ctx.scale(1+player.death*.35,1-player.death*.28);ctx.translate(-21,-27);ctx.globalAlpha=1-player.death*.15}else ctx.translate(-21,-27);if(player.star>0){ctx.strokeStyle='#fff06aaa';ctx.lineWidth=3;ctx.shadowColor='#fff06a';ctx.shadowBlur=20;ctx.beginPath();ctx.arc(21,28,39,0,7);ctx.stroke();ctx.shadowBlur=0}if(player.shield>0){ctx.strokeStyle='#72f1b8aa';ctx.lineWidth=3;ctx.shadowColor='#72f1b8';ctx.shadowBlur=18;ctx.beginPath();ctx.arc(21,28,37,0,7);ctx.stroke();ctx.shadowBlur=0}ctx.fillStyle='#263f52';ctx.beginPath();ctx.roundRect(7,18,27,32,9);ctx.fill();ctx.fillStyle='#65ce9b';ctx.beginPath();ctx.roundRect(17,3,25,23,8);ctx.fill();ctx.fillStyle='#8ff1ba';ctx.beginPath();ctx.arc(38,8,4,0,7);ctx.fill();ctx.fillStyle='#182a38';ctx.beginPath();ctx.arc(39,9,1.8,0,7);ctx.fill();ctx.fillStyle='#65ce9b';ctx.beginPath();ctx.moveTo(18,5);ctx.lineTo(11,0);ctx.lineTo(15,12);ctx.fill();ctx.fillStyle='#263f52';ctx.beginPath();ctx.moveTo(9,39);ctx.lineTo(2,49+run);ctx.lineTo(14,49+run);ctx.lineTo(18,39);ctx.fill();ctx.beginPath();ctx.moveTo(27,39);ctx.lineTo(28,49-run);ctx.lineTo(40,49-run);ctx.lineTo(36,37);ctx.fill();ctx.fillStyle='#f1a45c';ctx.beginPath();ctx.moveTo(18,26);ctx.lineTo(0,31);ctx.lineTo(18,34);ctx.fill();ctx.restore()}
  function loop(t){if(!running)return;const dt=Math.min(.035,(t-last)/1000);last=t;if(!paused)update(dt);draw();raf=requestAnimationFrame(loop)}
  $('startBtn').onclick=start;$('restartBtn').onclick=start;$('pauseBtn').onclick=()=>{if(running&&!dead){paused=!paused;tone('pause');$('pauseBtn').textContent=paused?'â–¶ PokraÄŤovat':'â…ˇ Pauza'}};$('soundBtn').onclick=()=>{sound=!sound;if(sound)initAudio();$('soundBtn').textContent='â™« Zvuk: '+(sound?'ano':'ne')};
  addEventListener('keydown',e=>{if(['Space','ArrowUp','KeyW'].includes(e.code)){e.preventDefault();jump()}if(e.code==='KeyP'){$('pauseBtn').click()}if(e.code==='ArrowLeft'||e.code==='KeyA')move(-1);if(e.code==='ArrowRight'||e.code==='KeyD')move(1);if(e.code==='Enter'&&!running)start()});
  $('jumpBtn').onclick=jump;$('leftBtn').onclick=()=>move(-1);$('rightBtn').onclick=()=>move(1);let touchX=0;game.addEventListener('touchstart',e=>{touchX=e.changedTouches[0].clientX},{passive:true});game.addEventListener('touchend',e=>{const dx=e.changedTouches[0].clientX-touchX;if(mode==='buttons'){if(Math.abs(dx)>35)move(dx>0?1:-1);else jump()}else jump()},{passive:true});
  for(let i=0;i<7;i++)clouds.push({x:Math.random()*W,y:35+Math.random()*110,s:15+Math.random()*22});setText();draw();
})();

